select * from customer
-- 1. Total records
SELECT COUNT(*) FROM customer;

-- 2. First 5 rows
SELECT * FROM customer LIMIT 5;

-- 3. Average income by gender
SELECT gender, AVG(purchase_amount)
FROM customer
GROUP BY gender;


--Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as revenue
from customer
group by gender


--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id ,purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >=(select avg(purchase_amount) from customer)


--Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased,round(avg(review_rating:: numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 6;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,
round (avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type



--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased,
round(100* sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
ORDER BY discount_rate desc
limit 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show...

-- with customer_type as (
-- select customer_id,previous_purchases,
-- case 
-- 	when previous_purchases = 1 then 'New'
-- 	when previous_purchases between 2 and 10 then 'returning'
-- 	else 'loyal'
-- 	end as customer_segment
-- from customer
-- )
-- select customer_segment,count(*) as "Number of customers"
-- from customer_tpye
-- group by customer_segment

-- Q7. Segment customers into New, Returning, and Loyal

WITH customer_type AS (
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)

SELECT
    customer_segment,
    COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment
ORDER BY COUNT(*) DESC;


--Q8. What are the top 3 most purchased products within each category?

-- with item_counts as (
-- select category,
-- item_purchased,
-- count(customer_id) as total_orders
-- row_number() over(partition by category order by count (customer_id) desc) as item_rank
-- from customer
-- group by category,iten_purchased
-- )
-- select item_rank,category,item_purchased,total_orders
-- from item_counts
-- where item_rank <= 3;

-- Q8. Top 3 most purchased products within each category

WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders
    FROM customer
    GROUP BY category, item_purchased
),
ranked_items AS (
    SELECT
        category,
        item_purchased,
        total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY total_orders DESC
        ) AS item_rank
    FROM item_counts
)

SELECT
    category,
    item_purchased,
    total_orders,
    item_rank
FROM ranked_items
WHERE item_rank <= 3
ORDER BY category, item_rank;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;



--Q10. What is the revenue contribution of each age group?

select age_group,
sum(purchase_amount) as total_revenue
from customer 
group by age_group
order by total_revenue desc;

